### ISSUE TITLE
Undefined offset: -2 in /var/www/html/admin/data.php

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/AdminLTE#145]
@ipv89 commented on [Wed Sep 21 2016](https://github.com/pi-hole/pi-hole/issues/709)

When viewing the apache error log it contains the following errors. 

Undefined offset: -2 in /var/www/html/admin/data.php on line 268
Undefined offset: -3 in /var/www/html/admin/data.php on line 269

Not sure if it is related but my graphs on the admin page are no longer loading but the stats are available through /api.php

**Comment by PromoFaux** [comment]
@ipv89 Those offset errors should be fixed in the next release of the webUI (See https://github.com/pi-hole/AdminLTE/pull/141)

Though as far as I can tell they are not related to the graphs not loading. How big is your `/var/log/pihole.log`? Do the graphs load OK at the beginning of the day?

**Comment by ipv89** [comment]
I have cleared the log file and it's still not showing the data just the spinning symbol. The query log, black and white lists are still visible via the webUI. 

The two doughnut graphs for what type of records and what resolvers were used are working. 

I am writing an add on to save the data from the log to a data base then run reports on the historical data. While doing this I have cleared the log multiple times but that shouldn't have any effect. 

No other errors in the Apache log or sys log.

**Comment by PromoFaux** [comment]
> I am writing an add on to save the data from the log to a data base then run reports on the historical data. 

Have you changed anything in `data.php`?

**Comment by ipv89** [comment]
I haven't changed any of the original code. I have also re installed the adminUI

**Comment by PromoFaux** [comment]
The spinning symbol will show if there is no data in the log, also. Though I'm guessing after a couple of queries they're still not showing?

If you open the developer menu in your browser (usually F12) do you get any console errors? Or Errors on the network tab?

**Comment by ipv89** [comment]
No errors there. all permissions seam ok.

**Comment by PromoFaux** [comment]
Can you try checking out the `devel` branch of the adminUI?

```
cd /var/www/html/admin
sudo git pull
sudo git checkout devel
```

**Comment by ipv89** [comment]
That has fixed the issue.

**Comment by PromoFaux** [comment]
Huh, OK, so whatever the issue is, it'll be fixed in the next release! Feel free to stay on the `devel` branch if you like, but be warned it can break at any time!

**Comment by ipv89** [comment]
Thanks for the help.
