### ISSUE TITLE
Avoid localhost request in stats?

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/AdminLTE#147]
@xoniq commented on [Fri May 06 2016](https://github.com/pi-hole/pi-hole/issues/496)

Is it possible to ignore requests coming from localhost (127.0.0.1)?
My server running pi-hole does lots of trafficking by itself, these are 80% of the traffic handled by the server, so the statistics are quite useless right now. (0,2% of today's traffic is ads)

---

@Mcat12 commented on [Fri May 06 2016](https://github.com/pi-hole/pi-hole/issues/496#issuecomment-217516037)

This is something we will look into.

---

@xoniq commented on [Fri May 06 2016](https://github.com/pi-hole/pi-hole/issues/496#issuecomment-217517568)

Thanks. Perhaps I can solve it by myself for the time being by alter the source from the dashboard to ignore localhost results when collecting the data.

---

@Mcat12 commented on [Fri May 06 2016](https://github.com/pi-hole/pi-hole/issues/496#issuecomment-217520899)

You'll probably have to edit some functions below [this line](https://github.com/pi-hole/AdminLTE/blob/master/data.php#L258).

---

@xoniq commented on [Fri May 06 2016](https://github.com/pi-hole/pi-hole/issues/496#issuecomment-217524828)

I have it solved a bit before (so it's a bit more at the beginning of parsing the data:

Modified:
```
function readInLog() {
    global $log;
    return count($log) > 1 ? $log :
        file("/var/log/pihole.log");
}
```
Into:
```
function readInLog() {
    global $log;
    $logData = count($log) > 1 ? $log :
        file("/var/log/pihole.log");
    // Avoid localhost entries to appear in the statistics
    return array_filter($logData, "avoidLocalhostEntries");
}
```
And added:
```
function avoidLocalhostEntries($var) {
    return (strpos($var, "127.0.0.1") === false);
}
```

Quick fix purely for display and calculations, but it gets the job done in a clean way.
This involves the whole dashboard. The chart is now more wavy instead of a giant wall without any gaps. And the data is now more useful to read.

---

@Mcat12 commented on [Fri May 06 2016](https://github.com/pi-hole/pi-hole/issues/496#issuecomment-217526495)

That seems like an easier fix that what I was thinking. :) Perhaps we'll add a config section to the web interface with stuff like this.

---

@xoniq commented on [Fri May 06 2016](https://github.com/pi-hole/pi-hole/issues/496#issuecomment-217531554)

To sketch out an example of how my situation have changed (and why this was really needed  for me:

Old situation:
![old](https://dl.dropboxusercontent.com/u/7528392/pihole-old.png)

Current situation:
![new](https://dl.dropboxusercontent.com/u/7528392/pihole-new.png)

Would be a nice addition to add my solution to a config section indeed, where you can add your own keywords to disable on both domain and hostname and whatever others want. That would be a more generic solution.

Then you can tell people to separate keywords by comma or something, and in the code convert the comma to pipe "|" to do something like this:

```
function avoidLocalhostEntries($var, $filter = '127.0.0.1,    apple.com, whatever') {
    // Explode filters on comma
    $filters = explode(',', $filter);
    // Trim whitespace around filter sections
    $filters = array_map('trim', $filters);
    // Put back together pipe-separated
    $filters_str = implode('|', $filters);
    // Avoid matching any filter sections
    return (preg_match('/(' . $filters_str . ')/', $var) == false);
}
```

In that case you only need to define a single line of comma separated values with or without whitespace, I clean it up in my example. (Example above is working fine, currently using it :-P)

Edit (Mcat12): You can add images with `![shown if it doesn't load](url of picture)`

**Comment by PromoFaux** [comment]
@xoniq
> 80% of the traffic handled by the server, so the statistics are quite useless right now. 

I've been playing about with the backend a lot the past couple of days. When you say localhost makes up about 80% of lookups, did you happen to notice if they were all requests for the hostname of the Pi-hole machine?

**Comment by dschaper** [comment]
I'll debate the term 'useless'. Unless we are generating the traffic, then the queries are coming from clients (even if the Pi-hole is acting as a client), and are very valid, just as valid as any other query. So far, from large queries from the Pi-hole, we've discovered a couple of issues with other daemons that are spewing lookups. We've found that Asus routers have a new keep-alive/phone home to Microsoft, and that a certain DLNA server likes to talk to Google, even though it has no need. Those two can now be blocked and they would not have been discovered if we had just squashed their queries from the data.

**Comment by Mcat12** [comment]
Fixed in #134

**Comment by cytec** [comment]
@Mcat12 seems like this got lost somehow? im still getting like 99% of my requests listed from localhost (127.0.0.1) which renders stats totally useless for me :/

**Comment by dschaper** [comment]
Are there any common domains that are being looked up from these localhost queries, or are they spread out over a lot of domains?

**Comment by DrMagPie** [comment]
Hi,

I'm playing around with pi-hole v5 beta.
and looks like I'm having same or similar issue.

pi hole server does a lot of self lookup. (looks up it's own hostname) 
<img width="1010" alt="Screenshot 2020-04-25 at 01 51 49" src="https://user-images.githubusercontent.com/23652900/80262836-5e63bd80-8697-11ea-80b5-a3d7e842bc0d.png">
<img width="510" alt="Screenshot 2020-04-25 at 01 52 57" src="https://user-images.githubusercontent.com/23652900/80262889-881ce480-8697-11ea-9697-15c00e0ba887.png">

it might be caused by me visiting admin page although I'm not sure about this.
